-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 20:13:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bombdash
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bombdash`;

-- -----------------------------------------------------
-- Schema bombdash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bombdash` DEFAULT CHARACTER SET utf8mb4;
SHOW WARNINGS;
USE `bombdash`;

-- -----------------------------------------------------
-- Table `bombdash`.`character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`character`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`character`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`icon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`icon`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`icon`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`profile`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`profile`
(
    `id`             INT         NOT NULL AUTO_INCREMENT,
    `player_id`      VARCHAR(75) NOT NULL,
    `name`           VARCHAR(45) NOT NULL,
    `color`          VARCHAR(45) NOT NULL,
    `highlight`      VARCHAR(45) NOT NULL,
    `character_type` INT         NOT NULL,
    `icon_type`      INT         NOT NULL,
    `global`         TINYINT(1)  NOT NULL,
    PRIMARY KEY (`id`, `player_id`, `character_type`, `icon_type`),
    INDEX `fk_profile_character1_idx` (`character_type` ASC) VISIBLE,
    INDEX `fk_profile_icon1_idx` (`icon_type` ASC) VISIBLE,
    INDEX `fk_profile_player1_idx` (`player_id` ASC) VISIBLE,
    CONSTRAINT `fk_profile_character1`
        FOREIGN KEY (`character_type`)
            REFERENCES `bombdash`.`character` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_profile_icon1`
        FOREIGN KEY (`icon_type`)
            REFERENCES `bombdash`.`icon` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_profile_player1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`server`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`server`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`player`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`player`
(
    `player_id`    VARCHAR(75) NOT NULL,
    `first_play`   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `last_ping`    DATETIME    NULL     DEFAULT CURRENT_TIMESTAMP,
    `last_profile` INT         NULL,
    `last_server`  INT         NULL,
    PRIMARY KEY (`player_id`),
    INDEX `fk_player_profile1_idx` (`last_profile` ASC) VISIBLE,
    INDEX `fk_player_server1_idx` (`last_server` ASC) VISIBLE,
    CONSTRAINT `fk_player_profile1`
        FOREIGN KEY (`last_profile`)
            REFERENCES `bombdash`.`profile` (`id`)
            ON DELETE SET NULL
            ON UPDATE CASCADE,
    CONSTRAINT `fk_player_server1`
        FOREIGN KEY (`last_server`)
            REFERENCES `bombdash`.`server` (`id`)
            ON DELETE SET NULL
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`status`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`status`
(
    `id`            INT         NOT NULL AUTO_INCREMENT,
    `name`          VARCHAR(45) NOT NULL,
    `forever_price` INT         NOT NULL,
    `month_price`   INT         NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`account`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`account`
(
    `player_id` VARCHAR(75)  NOT NULL,
    `email`     VARCHAR(45)  NOT NULL,
    `password`  VARCHAR(256) NOT NULL,
    `balance`   INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (`player_id`),
    INDEX `fk_accounts_players1_idx` (`player_id` ASC) VISIBLE,
    CONSTRAINT `fk_accounts_players1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`privilege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`privilege`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`privilege`
(
    `player_id` VARCHAR(75) NOT NULL,
    `status_id` INT         NOT NULL,
    `end`       TIMESTAMP   NULL,
    PRIMARY KEY (`player_id`, `status_id`),
    INDEX `fk_privilege_statuses1_idx` (`status_id` ASC) VISIBLE,
    INDEX `fk_privilege_account1_idx` (`player_id` ASC) VISIBLE,
    CONSTRAINT `fk_privilege_statuses1`
        FOREIGN KEY (`status_id`)
            REFERENCES `bombdash`.`status` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_privilege_account1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`account` (`player_id`)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`clan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`clan`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`clan`
(
    `id`          INT         NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(20) NOT NULL,
    `description` TEXT        NULL,
    `logo_url`    VARCHAR(45) NULL,
    `prefix`      VARCHAR(15) NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`registration`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`registration`
(
    `id`                INT          NOT NULL AUTO_INCREMENT,
    `email`             VARCHAR(45)  NOT NULL,
    `password`          VARCHAR(256) NOT NULL,
    `verification_code` VARCHAR(45)  NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`message`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`message`
(
    `id`      INT         NOT NULL AUTO_INCREMENT,
    `message` TEXT        NOT NULL,
    `from`    VARCHAR(75) NOT NULL,
    `to`      VARCHAR(75) NOT NULL,
    `date`    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`, `from`, `to`),
    INDEX `fk_messages_accounts1_idx` (`from` ASC) VISIBLE,
    INDEX `fk_messages_accounts2_idx` (`to` ASC) VISIBLE,
    CONSTRAINT `fk_messages_accounts1`
        FOREIGN KEY (`from`)
            REFERENCES `bombdash`.`account` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_messages_accounts2`
        FOREIGN KEY (`to`)
            REFERENCES `bombdash`.`account` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`server_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`server_chat`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`server_chat`
(
    `id`        INT           NOT NULL AUTO_INCREMENT,
    `message`   VARCHAR(1024) NOT NULL,
    `date`      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `from`      VARCHAR(75)   NOT NULL,
    `server_id` INT           NOT NULL,
    PRIMARY KEY (`id`, `from`, `server_id`),
    INDEX `fk_server_chat_players1_idx` (`from` ASC) VISIBLE,
    INDEX `fk_server_chat_server1_idx` (`server_id` ASC) VISIBLE,
    CONSTRAINT `fk_server_chat_players1`
        FOREIGN KEY (`from`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_server_chat_server1`
        FOREIGN KEY (`server_id`)
            REFERENCES `bombdash`.`server` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`game_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`game_history`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`game_history`
(
    `id`        INT      NOT NULL AUTO_INCREMENT,
    `date`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `server_id` INT      NOT NULL,
    PRIMARY KEY (`id`, `server_id`),
    INDEX `fk_game_history_server1_idx` (`server_id` ASC) VISIBLE,
    CONSTRAINT `fk_game_history_server1`
        FOREIGN KEY (`server_id`)
            REFERENCES `bombdash`.`server` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`score_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`score_type`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`score_type`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`score`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`score`
(
    `id`            INT         NOT NULL AUTO_INCREMENT,
    `value`         INT         NOT NULL,
    `score_type_id` INT         NOT NULL,
    `player_id`     VARCHAR(75) NOT NULL,
    PRIMARY KEY (`id`, `score_type_id`, `player_id`),
    INDEX `fk_score_score_type1_idx` (`score_type_id` ASC) VISIBLE,
    INDEX `fk_score_player1_idx` (`player_id` ASC) VISIBLE,
    CONSTRAINT `fk_score_score_type1`
        FOREIGN KEY (`score_type_id`)
            REFERENCES `bombdash`.`score_type` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_score_player1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`banlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`banlist`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`banlist`
(
    `player_id` VARCHAR(75) NOT NULL,
    `reason`    VARCHAR(45) NOT NULL,
    `banner`    VARCHAR(75) NULL,
    `end`       TIMESTAMP   NULL,
    PRIMARY KEY (`player_id`),
    INDEX `fk_banlist_player1_idx` (`player_id` ASC) VISIBLE,
    UNIQUE INDEX `player_id_UNIQUE` (`player_id` ASC) VISIBLE,
    INDEX `fk_banlist_player2_idx` (`banner` ASC) VISIBLE,
    CONSTRAINT `fk_banlist_player1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_banlist_player2`
        FOREIGN KEY (`banner`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`game_history_row`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`game_history_row`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`game_history_row`
(
    `game_history_id` INT         NOT NULL,
    `player_id`       VARCHAR(75) NOT NULL,
    PRIMARY KEY (`game_history_id`, `player_id`),
    INDEX `fk_game_history_has_player_player1_idx` (`player_id` ASC) VISIBLE,
    INDEX `fk_game_history_has_player_game_history1_idx` (`game_history_id` ASC) VISIBLE,
    CONSTRAINT `fk_game_history_has_player_game_history1`
        FOREIGN KEY (`game_history_id`)
            REFERENCES `bombdash`.`game_history` (`id`)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,
    CONSTRAINT `fk_game_history_has_player_player1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE CASCADE
            ON UPDATE RESTRICT
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`clan_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`clan_role`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`clan_role`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`clan_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`clan_person`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`clan_person`
(
    `player_id`    VARCHAR(75) NOT NULL,
    `clan_id`      INT         NOT NULL,
    `clan_role_id` INT         NOT NULL,
    PRIMARY KEY (`player_id`, `clan_id`, `clan_role_id`),
    INDEX `fk_clan_person_clan1_idx` (`clan_id` ASC) VISIBLE,
    INDEX `fk_clan_person_clan_role1_idx` (`clan_role_id` ASC) VISIBLE,
    CONSTRAINT `fk_clan_person_account1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`account` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_clan_person_clan1`
        FOREIGN KEY (`clan_id`)
            REFERENCES `bombdash`.`clan` (`id`)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,
    CONSTRAINT `fk_clan_person_clan_role1`
        FOREIGN KEY (`clan_role_id`)
            REFERENCES `bombdash`.`clan_role` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`banlist_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`banlist_history`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`banlist_history`
(
    `id`        INT         NOT NULL AUTO_INCREMENT,
    `player_id` VARCHAR(75) NOT NULL,
    `reason`    VARCHAR(45) NOT NULL,
    `banner`    VARCHAR(75) NULL,
    `end`       TIMESTAMP   NULL,
    PRIMARY KEY (`id`, `player_id`),
    UNIQUE INDEX `player_id_UNIQUE` (`player_id` ASC) VISIBLE,
    INDEX `fk_banlist_player2_idx` (`banner` ASC) VISIBLE,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    CONSTRAINT `fk_banlist_player20`
        FOREIGN KEY (`banner`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_banlist_history_player1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`particle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`particle`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`particle`
(
    `player_id`     VARCHAR(75) NOT NULL,
    `particle_type` VARCHAR(64) NOT NULL,
    `emit_type`     VARCHAR(64) NOT NULL,
    PRIMARY KEY (`player_id`, `particle_type`, `emit_type`),
    CONSTRAINT `fk_particle_player1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`prefix`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`prefix`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`prefix`
(
    `player_id` VARCHAR(75) NOT NULL,
    `text`      VARCHAR(45) NOT NULL,
    `speed`     INT         NOT NULL,
    PRIMARY KEY (`player_id`),
    CONSTRAINT `fk_prefix_player1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`prefix_animation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`prefix_animation`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`prefix_animation`
(
    `id`        INT         NOT NULL AUTO_INCREMENT,
    `color`     INT         NOT NULL,
    `player_id` VARCHAR(75) NOT NULL,
    PRIMARY KEY (`id`, `player_id`),
    INDEX `fk_prefix_animation_prefix1_idx` (`player_id` ASC) VISIBLE,
    CONSTRAINT `fk_prefix_animation_prefix1`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`prefix` (`player_id`)
            ON DELETE CASCADE
            ON UPDATE RESTRICT
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`month_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`month_score`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`month_score`
(
    `id`            INT         NOT NULL AUTO_INCREMENT,
    `value`         INT         NOT NULL,
    `score_type_id` INT         NOT NULL,
    `player_id`     VARCHAR(75) NOT NULL,
    PRIMARY KEY (`id`, `score_type_id`, `player_id`),
    INDEX `fk_score_score_type1_idx` (`score_type_id` ASC) VISIBLE,
    INDEX `fk_score_player1_idx` (`player_id` ASC) VISIBLE,
    CONSTRAINT `fk_score_score_type10`
        FOREIGN KEY (`score_type_id`)
            REFERENCES `bombdash`.`score_type` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_score_player10`
        FOREIGN KEY (`player_id`)
            REFERENCES `bombdash`.`player` (`player_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bombdash`.`persistent_logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bombdash`.`persistent_logins`;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bombdash`.`persistent_logins`
(
    `username`  VARCHAR(64) NOT NULL,
    `series`    VARCHAR(64) NOT NULL,
    `token`     VARCHAR(64) NOT NULL,
    `last_used` TIMESTAMP   NOT NULL,
    PRIMARY KEY (`series`)
)
    ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
